workflows:
  windows-app:
    name: Windows App
    instance_type: windows_x2
    environment:
      flutter: stable
    scripts:
      - name: Enable Windows
        script: |
          flutter config --enable-windows
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test
      - name: Build Windows app
        script: |
          flutter build windows
    artifacts:
      - build\windows\runner\**\*.exe

  macos-app:
    name: macOS App
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Enable macOS
        script: |
          flutter config --enable-macos
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test
      - name: Build macOS app
        script: |
          flutter build macos
    artifacts:
      - build/macos/Build/Products/Release/*.app

  linux-app:
    name: Linux App
    instance_type: linux_x2
    environment:
      flutter: stable
    scripts:
      - name: Enable Linux
        script: |
          flutter config --enable-linux
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test
      - name: Build Linux app
        script: |
          flutter build linux
    artifacts:
      - build/linux/x64/release/bundle/*

  github-release:
    name: GitHub Release
    instance_type: linux_x2
    environment:
      flutter: stable
      GITHUB_TOKEN: $GITHUB_TOKEN # Add your GitHub token here
    scripts:
      - name: Install GitHub CLI
        script: |
          sudo apt-get update
          sudo apt-get install gh -y
      - name: Build all desktop apps
        script: |
          flutter config --enable-windows
          flutter config --enable-macos
          flutter config --enable-linux
          flutter build windows
          flutter build macos
          flutter build linux
      - name: Create GitHub Release
        script: |
          gh release create $FCI_TAG \
            build/windows/runner/Release/*.exe \
            build/macos/Build/Products/Release/*.app \
            build/linux/x64/release/bundle/* \
            --title "$FCI_TAG" \
            --notes "Release $FCI_TAG"
    artifacts:
      - build/windows/runner/Release/*.exe
      - build/macos/Build/Products/Release/*.app
      - build/linux/x64/release/bundle/*

  scheduled-build:
    name: Scheduled Build
    instance_type: linux_x2
    environment:
      flutter: stable
      CODEMAGIC_API_TOKEN: $CODEMAGIC_API_TOKEN # Add your Codemagic API token here
    triggering:
      - schedule:
          pattern: "0 0 * * *"
          branch: main
    scripts:
      - name: Trigger github-release workflow
        script: |
          #!/bin/bash
          set -e

          # Get the github-release workflow ID
          WORKFLOW_ID=$(curl -s -H "x-auth-token: $CODEMAGIC_API_TOKEN" \
            "https://api.codemagic.io/v1/apps/$FCI_PROJECT_ID/workflows" | \
            jq -r '.[] | select(.name=="GitHub Release") | .id')

          # Trigger the github-release workflow
          curl -s -H "x-auth-token: $CODEMAGIC_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"branch": "main", "workflow_id": "'$WORKFLOW_ID'"}' \
            "https://api.codemagic.io/v1/apps/$FCI_PROJECT_ID/builds"

  pr-build:
    name: PR Build
    instance_type: linux_x2
    environment:
      flutter: stable
    triggering:
      - event: pull_request
        branch: main
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test
      - name: Analyze code
        script: |
          flutter analyze

  push-build:
    name: Push Build
    instance_type: linux_x2
    environment:
      flutter: stable
      CODEMAGIC_API_TOKEN: $CODEMAGIC_API_TOKEN # Add your Codemagic API token here
    triggering:
      - event: push
        branch: main
    scripts:
      - name: Trigger github-release workflow
        script: |
          #!/bin/bash
          set -e

          # Get the github-release workflow ID
          WORKFLOW_ID=$(curl -s -H "x-auth-token: $CODEMAGIC_API_TOKEN" \
            "https://api.codemagic.io/v1/apps/$FCI_PROJECT_ID/workflows" | \
            jq -r '.[] | select(.name=="GitHub Release") | .id')

          # Trigger the github-release workflow
          curl -s -H "x-auth-token: $CODEMAGIC_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"branch": "main", "workflow_id": "'$WORKFLOW_ID'"}' \
            "https://api.codemagic.io/v1/apps/$FCI_PROJECT_ID/builds"

  tag-build:
    name: Tag Build
    instance_type: linux_x2
    environment:
      flutter: stable
      CODEMAGIC_API_TOKEN: $CODEMAGIC_API_TOKEN # Add your Codemagic API token here
    triggering:
      - event: tag
        branch: "*"
    scripts:
      - name: Trigger github-release workflow
        script: |
          #!/bin/bash
          set -e

          # Get the github-release workflow ID
          WORKFLOW_ID=$(curl -s -H "x-auth-token: $CODEMAGIC_API_TOKEN" \
            "https://api.codemagic.io/v1/apps/$FCI_PROJECT_ID/workflows" | \
            jq -r '.[] | select(.name=="GitHub Release") | .id')

          # Trigger the github-release workflow
          curl -s -H "x-auth-token: $CODEMAGIC_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"branch": "$FCI_BRANCH", "workflow_id": "'$WORKFLOW_ID'"}' \
            "https://api.codemagic.io/v1/apps/$FCI_PROJECT_ID/builds"