workflows:
  windows-app:
    name: Windows App
    instance_type: windows_x2
    environment:
      flutter: stable
    scripts:
      - name: Enable Windows
        script: |
          flutter config --enable-windows
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test
      - name: Build Windows app
        script: |
          flutter build windows
    artifacts:
      - build\windows\runner\**\*.exe

  macos-app:
    name: macOS App
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Enable macOS
        script: |
          flutter config --enable-macos
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test
      - name: Build macOS app
        script: |
          flutter build macos
    artifacts:
      - build/macos/Build/Products/Release/*.app

  linux-app:
    name: Linux App
    instance_type: linux_x2
    environment:
      flutter: stable
    scripts:
      - name: Enable Linux
        script: |
          flutter config --enable-linux
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test
      - name: Build Linux app
        script: |
          flutter build linux
    artifacts:
      - build/linux/x64/release/bundle/*

